title: Yurii Kolesnykov
description: Senior iOS Sofware Developer
google_analytics: G-NJTM47YHS1
show_downloads: true
remote_theme: pages-themes/hacker@v0.2.0
github:
  pdf_url: "/Yurii Kolesnykov — Senior iOS Software Developer.pdf"
